### ISSUE TITLE
Make a practice plan

### ISSUE THREAD

**Issue by sixuanhan** [j55blanchet/dance-teacher-xr-unity#97]
Similar to what Julien and I have discussed earlier, it would be beneficial to have specific guides about _What_ to do next (which part of the song to practice) and different practice modes (drill, walkthrough, speed etc. the _How_ question).

**Comment by sixuanhan** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/xuanxuan/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/xuanxuan/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



action   verb | speed default | speed customizable? | reference/mirror default | reference/mirror customizable? | skeleton colorcode | LLM feedback | directing the user to a step
-- | -- | -- | -- | -- | -- | -- | --
mark | 0.5 | yes | reference | yes | yes | no | no
drill | 0.5 | yes | both | yes | yes | yes | no
do full out | 1 | no | mirror | no | no | yes | yes
  |   |   |   |   |   |   |  
voice   command: action verb + sectionID + modifiers |   |   |   |   |  
example   voice commands from the user: |   |   |   |   |   |  
"mark   section 1 with 0.5 speed and show both reference and mirror." |   |   |   |   |  
"drill   section 2 with only reference." |   |   |   |   |   |  
"do full out section   3." |   |   |   |   |   |   |  



</body>

</html>

**Comment by j55blanchet** [comment]
Is it useful to help the user keep track of what they've marked?

**Comment by j55blanchet** [comment]
For mark phase, the coach can ask users "do you feel like you know the moves now?" or similar question. The user can answer "yes", "no". If they say yes, we suggest they move onto a next activity. If they say no, we suggest they try making again.

We can extend this approach for other phases.



1. User finishes practicing a segment.
2. The system generates a list of potential next activities.
3a. The system asks the user a follow-up question to decide on which activity to suggest.
   * The user answers, and the system recommends a next activity accordingly.
3b. The system uses it's own evaluation to suggest a next activity.
4. The user chooses a next activity. Can be from the list or not.

**Comment by j55blanchet** [comment]
Make a little menu that enables click-based navigation to mark/drill/full out phases + associated configurable parameters.

**Comment by j55blanchet** [comment]
Drilling has a sub-progression:
* Increase in speed
* Remove the demo video (show mirror instead) 


Full out has sub-progression:
* Remove mirror, instead take a recording that's reviewed after the performance

**Comment by j55blanchet** [comment]
In dance studio, drills often focus on a particular part of the dance. You get tired, maybe sloppy, but are practicing something specific.

Full-out is a mock-performance, puts you in a different mental headspace. You put your best out there

**Comment by j55blanchet** [comment]
In drill, the user may want to focus on one particular aspect of their performance (like their legs, for instance). So we don't want to give them feedback which may not be relevant to what they're actually trying to practice.

**Comment by j55blanchet** [comment]
Done as part of MOCO submission
